packages:
  - 'extensions/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@shopify/shopify_function': true
  core-js: true
  esbuild: true
  prisma: true
  unrs-resolver: true
